-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local function GetNil(Name, DebugId)
	for _, Object in getnilinstances() do
		if Object.Name == Name and Object:GetDebugId() == DebugId then
			return Object
		end
	end
end

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local LocalPlayer = game:GetService("Players").LocalPlayer
local Workspace = game:GetService("Workspace")

-- 检测玩家是否活着
local function IsPlayerAlive(player)
    if not player then return false end
    local character = player.Character
    if not character then return false end
    local humanoid = character:FindFirstChild("Humanoid")
    if not humanoid then return false end
    return humanoid.Health > 0
end

-- 检测是否有掩体阻挡（射线检测）
local function HasCover(startPos, endPos)
    local params = RaycastParams.new()
    params.FilterType = Enum.RaycastFilterType.Blacklist
    params.FilterDescendantsInstances = {LocalPlayer.Character}
    params.IgnoreWater = true
    
    local rayResult = Workspace:Raycast(startPos, (endPos - startPos), params)
    
    if rayResult then
        local hit = rayResult.Instance
        -- 检查击中的是否是玩家角色
        if hit and hit.Parent and hit.Parent:FindFirstChild("Humanoid") then
            return false -- 击中了玩家，没有掩体
        end
        return true -- 击中了物体，有掩体
    end
    return false -- 没有击中任何物体，无掩体
end

-- 获取100米内符合条件的敌方玩家
local function GetBestEnemy()
    local character = LocalPlayer.Character
    if not character then return nil, nil, nil end
    
    local rootPart = character:FindFirstChild("HumanoidRootPart")
    if not rootPart then return nil, nil, nil end
    
    local currentPos = rootPart.Position
    local bestTarget = nil
    local bestDistance = 100 -- 100米范围
    local bestPos = nil
    
    for _, player in ipairs(Players:GetPlayers()) do
        if player ~= LocalPlayer then
            -- 检查是否活着
            if not IsPlayerAlive(player) then
                continue
            end
            
            -- 检查是否是敌方
            local team1 = LocalPlayer.Team
            local team2 = player.Team
            if team1 and team2 and team1 == team2 then
                continue -- 同队跳过
            end
            
            local targetChar = player.Character
            if not targetChar then continue end
            
            local head = targetChar:FindFirstChild("Head")
            if not head then continue end
            
            local distance = (currentPos - head.Position).Magnitude
            if distance > 100 then
                continue -- 超出100米范围
            end
            
            -- 检查是否有掩体阻挡
            if HasCover(currentPos, head.Position) then
                continue -- 有掩体阻挡，跳过
            end
            
            -- 选择最近的敌人
            if distance < bestDistance then
                bestDistance = distance
                bestTarget = player
                bestPos = head.Position
            end
        end
    end
    
    return bestTarget, bestPos, bestDistance
end

-- 获取两个位置用于发送
local function GetTargetPositions()
    local target, targetPos, distance = GetBestEnemy()
    
    if target and targetPos then
        -- 第一个位置：敌人头部位置
        local pos1 = targetPos
        -- 第二个位置：敌人头部上方偏移一点
        local pos2 = targetPos + Vector3.new(0, 1, 0)
        return pos1, pos2, true
    end
    
    -- 如果没有找到符合条件的敌人，返回nil
    return nil, nil, false
end

-- 发送事件函数
local function FireShootEvent()
    local Event = game:GetService("ReplicatedStorage").ServerEvents.Shoot
    if not Event then return end
    
    local pos1, pos2, hasTarget = GetTargetPositions()
    
    -- 如果没有符合条件的敌人，不发送
    if not hasTarget then
        print("没有符合条件的敌方目标，跳过发送")
        return
    end
    
    -- 检查本地玩家是否活着
    if not IsPlayerAlive(LocalPlayer) then
        print("本地玩家已死亡，停止发送")
        return
    end
    
    -- 检查本地玩家角色是否存在
    if not LocalPlayer.Character then
        print("本地玩家角色不存在，停止发送")
        return
    end
    
    Event:FireServer(
        {
            currentShots = 1,
            LoadedAnimations = true,
            hapticLeftTrigger = false,
            animationList = {
                boltCycleAnimation = GetNil("boltCycle", "0_2701986"),
                runAnimation = GetNil("run", "0_2701989"),
                aimAnimation = GetNil("aim", "0_2701983"),
                aimFireAnimation = GetNil("aimFire", "0_2701985"),
                meleeAnimation = GetNil("melee", "0_2701988"),
                hipFireAnimation = GetNil("hipFire", "0_2701987"),
                reloadAnimation = GetNil("reload", "0_2701984"),
                equipAnimation = GetNil("equip", "0_2701982")
            },
            Sounds = LocalPlayer.Character["Gewehr 98"].Hold.Sounds,
            Character = LocalPlayer.Character,
            clientCanFire = true,
            handleAction = function(arg1, arg2, arg3)
                return
            end,
            LoadedEvents = true,
            Tool = LocalPlayer.Character["Gewehr 98"],
            hapticRightTrigger = false,
            actionBinds = {
                Shoot = {
                    true,
                    Enum.UserInputType.MouseButton1,
                    Enum.KeyCode.ButtonR2
                },
                Melee = {
                    true,
                    Enum.UserInputType.MouseButton3,
                    Enum.KeyCode.V,
                    Enum.KeyCode.ButtonB
                },
                Aim = {
                    true,
                    Enum.UserInputType.MouseButton2,
                    Enum.KeyCode.Q,
                    Enum.KeyCode.ButtonL2
                },
                Perspective = {
                    true,
                    Enum.KeyCode.E,
                    Enum.KeyCode.ButtonR3
                },
                Reload = {
                    true,
                    Enum.KeyCode.R,
                    Enum.KeyCode.ButtonX
                }
            },
            isVibrationSupported = true,
            meleeTrail = LocalPlayer.Character["Gewehr 98"].Hold.MeleeTrail,
            Player = LocalPlayer,
            hapticLeftHand = false,
            RecoilPattern = {
                {
                    1,
                    10,
                    -1,
                    0.77,
                    -0.1
                },
                {
                    6,
                    5,
                    -1,
                    0.77,
                    -0.66666666666667
                },
                {
                    11,
                    5,
                    -1,
                    0.77,
                    0.66666666666667
                }
            },
            Cycle = true,
            resetBool = {
                meleeHoldRepeat = false,
                shootHoldRepeat = false
            },
            hapticLarge = true,
            Camera = workspace.Camera,
            lastClick = 1783283348.7353,
            hapticRightHand = false,
            hapticSmall = true
        },
        pos1,
        true,
        1,
        {},
        pos2
    )
    
    print("已发送射击事件，目标: " .. tostring(pos1) .. ", 距离: " .. tostring(1) .. "米")
end

-- 主循环 - 每2秒执行1次
while wait(2) do
    pcall(function()
        FireShootEvent()
    end)
end